### ISSUE TITLE
求docker版本

### ISSUE THREAD

**Issue by moonlike-moe** [HanHai-Space/FlowSilicon#1]

**Comment by HanHai-Space** [comment]
已上传

**Comment by springandme** [comment]
是否提供提供 ARM 版本的镜像，使用镜像`ghcr.io/hanhai-space/flowsilicon:1.3.8`在甲骨文ARM服务器上无法运行

![Image](https://github.com/user-attachments/assets/8c86ebff-18bd-4ea3-a108-3c2ff02bda0f)

`docker-compose.yml`
```
networks:
  1panel-network:
    external: true


services:
  flowsilicon:
    image: ghcr.io/hanhai-space/flowsilicon:1.3.8
    container_name: flowsilicon
    restart: unless-stopped
    ports:
      - "20016:3016"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - FLOWSILICON_GUI=0
    networks:
      - 1panel-network
```


```shell
➜  FlowSilicon ll
total 4.0K
-rw-r--r-- 1 root root 391 Mar 27 13:57 docker-compose.yml
➜  FlowSilicon docker-compose up -d
[+] Running 2/2
 ✔ Container flowsilicon                                                                                                                                      Started                                 0.3s
 ! flowsilicon The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                         0.0s
➜  FlowSilicon docker-compose logs -f
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
flowsilicon  | exec ./flowsilicon: exec format error
➜  FlowSilicon docker-compose ps -a
NAME          IMAGE                                    COMMAND           SERVICE       CREATED              STATUS                            PORTS
flowsilicon   ghcr.io/hanhai-space/flowsilicon:1.3.8   "./flowsilicon"   flowsilicon   About a minute ago   Restarting (255) 44 seconds ago
➜  FlowSilicon 
```
